project_id = "yzlqjyurbcxzqlsypkjh"

[functions.send-notification]
verify_jwt = false

[functions.cleanup-old-files]
verify_jwt = false

[functions.telegram-order-notify]
verify_jwt = false

[functions.refresh-hottest-sale]
verify_jwt = false
